CREATE TABLE company
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_name VARCHAR(255)                            NOT NULL,
    country      VARCHAR(2)                              NOT NULL,
    symbol       VARCHAR(255)                            NOT NULL,
    website      VARCHAR(255),
    email        VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_company PRIMARY KEY (id)
);

CREATE TABLE stocks
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_id            BIGINT                                  NOT NULL,
    market_capitalization DECIMAL(20, 2)                          NOT NULL,
    share_outstanding     DECIMAL(20, 2)                          NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_stocks PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(50)                             NOT NULL,
    email         VARCHAR(100)                            NOT NULL,
    password_hash VARCHAR(255),
    provider_type VARCHAR(50),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE stocks
    ADD CONSTRAINT FK_STOCKS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);