name: SonarCloud

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  sonar:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: StockMarketSpringAPI

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: stock_market_db_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: dido12
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Prepare Gradle wrapper
        run: |
          sed -i 's/\r$//' gradlew
          chmod +x gradlew || true

      - name: Wait for PostgreSQL
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 && break
            sleep 1
          done

      - name: Run tests with coverage
        run: bash ./gradlew test jacocoTestReport 

      - name: SonarCloud scan
        uses: SonarSource/sonarqube-scan-action@v5.3.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=dido1043
            -Dsonar.projectKey=dido1043_StockMarket
            -Dsonar.projectBaseDir=StockMarketSpringAPI
            -Dsonar.sources=src/main
            -Dsonar.tests=src/test
            -Dsonar.java.binaries=build/classes,build/classes/java/main
