name: SonarCloud

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: read

jobs:
  sonar:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: StockMarketSpringAPI

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: stock_market_db_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: dido12
        options: >-
          --health-cmd "pg_isready -U postgres -d stock_market_db_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Prepare Gradle wrapper
        run: |
          sed -i 's/\r$//' gradlew
          chmod +x gradlew || true

      - name: Wait for PostgreSQL (container)
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 && break
            -Dsonar.projectBaseDir=.
            -Dsonar.sources=src/main
            -Dsonar.tests=src/test
            -Dsonar.java.binaries=build/classes/java/main
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
